language: go

go:
  - 1.13.x
  - 1.14.x

before_script:
  - go get github.com/golang/lint/golint
  - go get github.com/fzipp/gocyclo
  - go get

script:
  - go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

